### ISSUE TITLE
Failing builds on Amplify

### ISSUE THREAD

**Issue by daine** [cds-snc/design-gc-conception#776]
Our amplify builds are failing. It looks like the last successful deployment was on March 6th. Any new content changes to our documentation website after that are not being released to production.

The website is still up because of the CI/CD build pipeline, it's just serving stale content (before March 6th).

**Comment by daine** [comment]
Here is the provision logs (build env) for the last successful run on March 4th
<img width="1084" alt="Screenshot 2024-03-13 at 4 07 13 PM" src="https://github.com/cds-snc/design-gc-conception/assets/916044/3454c72c-6cf5-4f26-8ba0-6122afa99240">

<img width="704" alt="Screenshot 2024-03-13 at 4 06 25 PM" src="https://github.com/cds-snc/design-gc-conception/assets/916044/587873c9-26a0-423a-9828-573c6851b3b5">

**Comment by daine** [comment]
The failing build log is as follows:
```bash
2024-03-13T14:52:03.739Z [INFO]: # Executing command: npm run build
2024-03-13T14:52:04.000Z [INFO]: > gcds-documentation@0.1.8 build
                                 > npm-run-all build:sass --parallel build:*
2024-03-13T14:52:04.371Z [INFO]: > gcds-documentation@0.1.8 build:sass
                                 > node-sass src/styles -o src/styles
2024-03-13T14:52:06.509Z [WARNING]: /codebuild/output/src699451704/src/gcds-docs/node_modules/node-sass/lib/binding.js:15
                                    throw new Error(errors.missingBinary());
                                    ^
                                    Error: Missing binding /codebuild/output/src699451704/src/gcds-docs/node_modules/node-sass/vendor/linux-x64-108/binding.node
                                    Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 18.x
                                    Found bindings for the following environments:
                                    - Linux 64-bit with Node.js 16.x
                                    This usually happens because your environment has changed since running `npm install`.
                                    Run `npm rebuild node-sass` to download the binding for your current environment.
                                    at module.exports (/codebuild/output/src699451704/src/gcds-docs/node_modules/node-sass/lib/binding.js:15:13)
                                    at Object.<anonymous> (/codebuild/output/src699451704/src/gcds-docs/node_modules/node-sass/lib/index.js:13:35)
                                    at Module._compile (node:internal/modules/cjs/loader:1256:14)
                                    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
                                    at Module.load (node:internal/modules/cjs/loader:1119:32)
                                    at Module._load (node:internal/modules/cjs/loader:960:12)
                                    at Module.require (node:internal/modules/cjs/loader:1143:19)
                                    at require (node:internal/modules/cjs/helpers:119:18)
                                    at Object.<anonymous> (/codebuild/output/src699451704/src/gcds-docs/node_modules/node-sass/bin/node-sass:10:10)
                                    at Module._compile (node:internal/modules/cjs/loader:1256:14)
                                    Node.js v18.18.2
2024-03-13T14:52:06.525Z [WARNING]: ERROR: "build:sass" exited with 1.
2024-03-13T14:52:06.535Z [ERROR]: !!! Build failed
2024-03-13T14:52:06.535Z [ERROR]: !!! Error: Command failed with exit code 1
```

**Comment by daine** [comment]
Replaced `node-sass` with `sass`, and that fixed the issue
